/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tgs1;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class GUI_obt extends javax.swing.JFrame {
    private Obat bat;
    private informasi info;
    private DefaultTableModel tableModel;
    /**
     * Creates new form GUI_Dokter
     */
    public GUI_obt() {
        initComponents();
          tableModel = new DefaultTableModel(new Object[]{"Nama Obat", "Jumlah","Dosis"}, 0);
        jTable1.setModel(tableModel);
    }
    
    public Connection conn;
    
    public void koneksi() throws SQLException {
        try {
            conn = null;
            Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost/oop_informasirs?user=root&amp;password=");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_obt.class.getName()).log(Level.SEVERE,null, ex);
        } catch (SQLException e) {
            Logger.getLogger(GUI_obt.class.getName()).log(Level.SEVERE,null, e);
        } catch (Exception es) {
            Logger.getLogger(GUI_obt.class.getName()).log(Level.SEVERE,null, es);
        }
    }
    public void tampil() {
        DefaultTableModel tabelhead = new DefaultTableModel();
        tabelhead.addColumn("Kode Obat");
        tabelhead.addColumn("Nama Obat");
        tabelhead.addColumn("Jumlah");
        tabelhead.addColumn("Dosis");
        try {
            koneksi();
            String sql = "SELECT * FROM tb_obt";
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while (res.next()) {
            tabelhead.addRow(new Object[]{res.getString(2),res.getString(3), res.getString(4), res.getString(5),});
            }
            JTable1.setModel(tabelhead);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, &quot;BELUMTERKONEKSI&quot;);
        }
}
    
    public void refresh() {
new GUI_obt().setVisible(true);
this.setVisible(false);
}
    
    public void insert() {
String Nim = txtNim.getText();
String Nama = txtNama.getText();
String jk;
if (radiobtnLaki.isSelected()) {

jk = &quot;L&quot;;
} else {
jk = &quot;P&quot;;
}
String Prodi = txtProdi.getText();
String Ang = txtAngkatan.getText();
String alamat = txtAlamat.getText();
try {
koneksi();
Statement statement = conn.createStatement();
statement.executeUpdate(&quot;INSERT INTO tb_mahasiswa (nim,
nama,jk, prodi, th_angkatan,alamat)&quot;
+ &quot;VALUES(&#39;&quot; + Nim + &quot;&#39;,&#39;&quot; + Nama + &quot;&#39;,&#39;&quot; + jk
+ &quot;&#39;,&#39;&quot; + Prodi + &quot;&#39;,&#39;&quot; + Ang + &quot;&#39;,&#39;&quot; + alamat + &quot;&#39;)&quot;);
statement.close();
JOptionPane.showMessageDialog(null, &quot;Berhasil Memasukan
Data Mahasiswa!&quot; + &quot;\n&quot; + alamat);
} catch (Exception e) {
JOptionPane.showMessageDialog(null, &quot;Terjadi Kesalahan
Input!&quot;);
}
refresh();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamaobat = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Hapus = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtdosis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INFORAMSI OBAT");

        jLabel2.setText("Nama Obat");

        jLabel3.setText("Jumlah");

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Obat", "Jumlah", "Dosis"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jLabel4.setText("Dosis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnamaobat, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtjumlah)
                            .addComponent(txtdosis)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Simpan)
                        .addGap(18, 18, 18)
                        .addComponent(Hapus)
                        .addGap(18, 18, 18)
                        .addComponent(Close))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(766, 766, 766))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnamaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Simpan)
                            .addComponent(Hapus)
                            .addComponent(Close))))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
                                 
    try {
        String namaObat = txtnamaobat.getText();
        String jumlah = txtjumlah.getText();
        String dosis = txtdosis.getText();
        // Validasi input (Anda dapat menambahkan validasi lain sesuai kebutuhan)
        if (namaObat.isEmpty() || jumlah.isEmpty() || dosis.isEmpty()) {
            throw new IllegalArgumentException("Semua kolom harus diisi");
        }
        // Membuat objek Obat
        Obat obat = new Obat(namaObat, jumlah, dosis);
        // Menambahkan data ke tabel
        Object[] rowData = { obat.getNamaObat(), obat.getJumlah(), obat.getDosis() };
        tableModel.addRow(rowData);
        // Membersihkan input setelah disimpan (opsional)
        txtnamaobat.setText("");
        txtjumlah.setText("");
        txtdosis.setText("");
    } catch (Exception e) {
        // Menangani pengecualian, Anda dapat mencatat pesan kesalahan atau menampilkan pesan kesalahan
        JOptionPane.showMessageDialog(this, "Error menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SimpanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
    int rowCount = dataModel.getRowCount();
    
    // Menghapus semua baris dari model tabel
    for (int i = rowCount - 1; i >= 0; i--) {
        dataModel.removeRow(i);
    }
    }//GEN-LAST:event_HapusActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_obt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_obt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_obt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_obt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_obt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdosis;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnamaobat;
    // End of variables declaration//GEN-END:variables
}
